-- Queue — emergency fallback directory
--
-- Stage one of Queue-Ambulance-Stage1-Scope.md. Backs the promise "we find you
-- an ambulance, and if we can't, we tell you instantly and hand you the numbers
-- that will" — specifically the second half, which must work at zero supply.
--
-- Read by anon on purpose: the fallback has to render before login, on a cold
-- install, and is cached on-device so it survives having no network at all.
--
-- ---------------------------------------------------------------------------
-- THIS TABLE SHIPS EMPTY. THAT IS DELIBERATE.
--
-- A wrong number in an emergency is worse than no number — the caller burns the
-- seconds that mattered on a dead line, having been told by us that it would
-- work. Every row must be dialled by a person who confirms it answers, confirms
-- it is the service it claims to be, and records who checked and when.
--
-- Numbers must not be scraped, inferred, copied from search results, or
-- generated by a model. See the template at the bottom of this file.
-- ---------------------------------------------------------------------------

create table emergency_directory (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  kind               text not null
                       check (kind in ('national','state','hospital_ae','private_fleet')),
  phone              text not null,
  alt_phone          text,

  -- Coarse coverage for v1. Proximity ranking waits on real coordinates —
  -- production currently has 2 hospitals, neither geocoded.
  country            text not null default 'Nigeria',
  state              text,
  city               text,
  latitude           double precision,
  longitude          double precision,

  -- Lower sorts first within a coverage area. National emergency lines should
  -- outrank everything else regardless of distance.
  priority           smallint not null default 100,
  notes              text,

  is_active          boolean not null default true,

  -- Verification is not optional. An entry that has never been dialled is not
  -- servable, which is why last_verified_at is NOT NULL with no default —
  -- inserting a row forces the author to state when it was checked.
  last_verified_at   timestamptz not null,
  verified_by        text not null,
  verification_note  text,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index emergency_directory_lookup_idx
  on emergency_directory (country, state, priority)
  where is_active;

comment on column emergency_directory.last_verified_at is
  'When a human last dialled this number and confirmed it answers. Entries older than the decay window are hidden from the public view.';

-- ---------------------------------------------------------------------------
-- Decay
--
-- Entries rot silently: a hospital changes provider, a line is disconnected, a
-- service is defunded. Rather than trusting that someone notices, an entry
-- stops being served once its verification goes stale. Failing closed here
-- means the app shows fewer numbers, never wrong ones.
-- ---------------------------------------------------------------------------

create or replace function emergency_directory_ttl_days()
returns integer
language sql
immutable
parallel safe
as $$ select 90 $$;

-- Clients read this view, never the base table. The view is owned by the
-- migration role and does not set security_invoker, so it can expose rows to
-- anon without granting anon anything on emergency_directory itself.
create view emergency_directory_public as
  select id, name, kind, phone, alt_phone,
         country, state, city, latitude, longitude,
         priority, notes, last_verified_at
    from emergency_directory
   where is_active
     and last_verified_at > now() - (emergency_directory_ttl_days() || ' days')::interval
   order by priority, name;

comment on view emergency_directory_public is
  'Servable emergency numbers: active, and verified within the decay window. Never query emergency_directory directly from a client.';

alter table emergency_directory enable row level security;

-- No anon/authenticated policy on the base table at all — the view is the only
-- read path. Platform admins manage rows through the dashboard.
create policy emergency_directory_admin_all on emergency_directory
  for all
  using (exists (
    select 1 from platform_admins pa
     join users u on u.id = pa.user_id
    where u.auth_id = auth.uid() and pa.is_active
  ))
  with check (exists (
    select 1 from platform_admins pa
     join users u on u.id = pa.user_id
    where u.auth_id = auth.uid() and pa.is_active
  ));

revoke all on emergency_directory from anon, authenticated;
grant select on emergency_directory_public to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Populating this table
--
-- Template — fill in only after dialling. Do not uncomment with placeholder
-- values; an unverified row is worse than an empty table, because the app will
-- present it to someone in crisis as a working number.
--
--   insert into emergency_directory
--     (name, kind, phone, country, state, city, priority, last_verified_at, verified_by, verification_note)
--   values
--     ('<official service name>', 'national', '<E.164>', 'Nigeria', null, null, 1,
--      now(), '<who dialled it>', '<what happened when they called>');
--
-- Suggested first pass, in priority order:
--   1. national  — the country-wide emergency line
--   2. state     — state ambulance / emergency service for each launch state
--   3. hospital_ae — A&E direct lines for hospitals already onboarded
--   4. private_fleet — certified operators (also the first step of supply
--                      onboarding; a directory listing costs them nothing)
-- ---------------------------------------------------------------------------
